AWSTemplateFormatVersion: 2010-09-09
Description: Part 1 - Build a webapp stack with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro      # EC2 instance type
      ImageId: ami-0b4624933067d393a  # Replace with the desired AMI ID
      KeyName: ohio-key          # Replace with your SSH key pair name
      SecurityGroupIds:
        - !Ref WebAppSecurityGroup    # Associating the security group created above

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Join [ '_', [ webapp-security-group, karishma ] ] 
      GroupDescription: 'Allow inbound SSH and HTTP traffic'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Allows SSH from any IP
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Allows HTTP from any IP
